### ISSUE TITLE
no file submitted indicator for judges + block review / grading

### ISSUE THREAD

**Issue by Sparkiee** [Sparkiee/final-project-se#56]
If no file was submitted by the student, the judge shouldn't be able to review the assignment

![image](https://github.com/user-attachments/assets/028c56af-f75e-4040-b5cb-8f1b1062f3cc)

![image](https://github.com/user-attachments/assets/3a73025c-03e5-4a0a-89ff-b1486a61ed60)

**Comment by Adam19255** [comment]
Did that before you opened it boiiiiii
