### ISSUE TITLE
Problem with opening specific submission

### ISSUE THREAD

**Issue by Adam19255** [Sparkiee/final-project-se#57]
When I go to open a submission for a specific project I can't choose which type it is (graded/reviewed)
![image](https://github.com/user-attachments/assets/3a368ad8-020d-469c-9bad-d67f04e0739e)

After opening the projects there is no name to them (even if I pick one from the preset "דוח אלפה")
![image](https://github.com/user-attachments/assets/8950a17b-801f-4992-9f59-19d2614e548a)

Both are opened with graded/reviewed set to false

**Comment by Sparkiee** [comment]
fixed
